Below is a list of committed partners who are working with us to take the MY World survey out into their communities:<br><br>
<div class="accordion">
<h3><span  class="box arrow-down active-box color-blue"></span><a href="#">UN Agencies</a></h3>
<article>

<ul>
<li><a href='#'>Office of the UN Resident Coordinator</a></li>
<li><a href='http://www.unfoundation.org'>UN Foundation</a></li>
<li><a href='http://www.un.by'>UN in Belarus</a></li>
<li><a href='#'>UN in Maruitius</a></li>
<li><a href='http://www.unapcict.org'>UN-APCICT/ESCAP</a></li>
<li><a href='#'>UNA: Focus on Women</a></li>
<li><a href='http://www.unaids.org'>UNAIDS</a></li>
<li><a href='http://www.unanima-international.org/eng/'>UNANIMA</a></li>
<li><a href='#'>UNDESA-DSPD Focal Point on Cooperatives</a></li>
<li><a href='http://www.undp.org'>UNDP</a></li>
<li><a href='http://www.undp.org/rw'>UNDP in Rwanda</a></li>
<li><a href='http://www.undp.or.id'>UNDP Indonesia</a></li>
<li><a href='#'>UNDP Regional Bureau of Arab States</a></li>
<li><a href='#'>UNFPA</a></li>
<li><a href='http://www.indonesia.unfpa.org'>UNFPA Indonesia</a></li>
<li><a href='#'>UNICA</a></li>
<li><a href='http://www.unicef.org/ecuador'>UNICEF Ecuador</a></li>
<li><a href='http://www.unicef.org/indonesia'>UNICEF Indonesia</a></li>
<li><a href='#'>UNICEF Rwanda</a></li>
<li><a href='http://www.un.org.al'>United Nations Albania</a></li>
<li><a href='http://www.unaserbia.rs, www.bimun-unaserbia.org'>United Nations Association of Serbia</a></li>
<li><a href='http://www.unicef.org/costarica'>United Nations Costa Rica</a></li>
<li><a href='http://www.un.or.th'>United Nations in Thailand</a></li>
<li><a href='http://www.un.org.au'>United Nations Information Centre Canberra</a></li>
<li><a href='http://www.unicmanila.org'>United Nations Information Centre Manila</a></li>
<li><a href='http://www.unis.org'>United Nations International School</a></li>
<li><a href='http://www.un-ngls.org'>United Nations Non-Governmental Liaison Service</a></li>
<li><a href='http://www.un.or.id/en/'>United Nations Office of the Resident Coordinator</a></li>
<li><a href='http://www.unv.org'>United Nations Volunteers </a></li>
<li><a href='#'>UNMC Youth Digital Advocates</a></li>
<li><a href='http://www.unorcid.org/'>UNORCID</a></li>
<li><a href='http://www.sportanddev.org/connect/organisation.cfm?org=90'>UNOSDP</a></li>
<li><a href='http://www.un.org.np'>UNRCHCO Nepal</a></li>
<li><a href='http://www.un.org.mv'>UNRCO Maldives</a></li>
<li><a href='http://www.vun.org'>Virtual United Nations</a></li>
<li><a href='http://www.wfuna.org'>World Federation of United Nations Association</a></li>
       
</ul>

</article>
<h3><span class="box arrow-down color-green"></span><a href="#">Civil Society</a></h3>
<article>

<ul>
 <li><a href='http://www.abc4all.net'>ABC4All</a></li>
<li><a href='http://www.abs-cbn.com'>ABS CBN</a></li>
<li><a href='http://www.sinergia.org.ve'>AC Sinergia</a></li>
<li><a href='http://www.agrasri.org.in'>Academy of Grassroots Studies and Research of</a></li>
<li><a href='http://www.acehinstitute.org'>Aceh Institute</a></li>
<li><a href='http://www.aciamericas.coop'>ACI Americas</a></li>
<li><a href='http://www.acot.edu/'>ACOT</a></li>
<li><a href='http://www.facebook.com/pages/ACTIVISTASENEGAL/'>Activista/Senegal</a></li>
<li><a href='http://www.acudes.org'>ACUDES</a></li>
<li><a href='http://www.acefnigeria.wordpress.com'>Africa Citizen's Empowerment Foundation</a></li>
<li><a href='http://www.africanviews.org'>African Views Organisation</a></li>
<li><a href='http://www.aypad.com'>african youth network for paece and developme</a></li>
<li><a href='http://www.afriyan.com'>AfriYAN AOC</a></li>
<li><a href='http://www.aiesec.org/'>AIESEC Local Committe Setif</a></li>
<li><a href='http://www.aciamericas.coop'>Alianza Cooperativa Internacional para las Am</a></li>
<li><a href='http://www.rebelatecontralapobreza.org'>Alianza Espanola contra la Pobreza</a></li>
<li><a href='http://www.alianzaporlaninez.org.co'>Alianza por la NiÌ±ez Colombiana</a></li>
<li><a href='http://www.alohamovementproject.com'>Aloha Movement Project</a></li>
<li><a href='http://www.anglicanalliance.org'>Anglican Alliance</a></li>
<li><a href='#'>Asosiasi Pendamping Perempuan Usaha Kecil</a></li>
<li><a href='http://www.indoace.or.id'>Association for Community Empowerment</a></li>
<li><a href='http://www.axios.org.mx/index.html'>Axios Mision-Mujer </a></li>
<li><a href='http://www.bahai.us/'>Bahai Office of Public Affairs</a></li>
<li><a href='http://www.bangladeshyouthforum.weebly.com'>Bangladesh National Youth Forum</a></li>
<li><a href='http://www.berlin-civil-society-center.org'>Berlin Civil Society Center</a></li>
<li><a href='http://www.bigstepsoutreach.wordpress.com'>Big Steps Outreach Network(BONET) Cameroon</a></li>
<li><a href='http://scouts.org.ph'>Boy Scouts of the Philippines</a></li>
<li><a href='http://www.bridgesport.org'>BridgeSport</a></li>
<li><a href='http://http://britishcouncil-climatechampions.ning.com'>British Council Climate Champions Network</a></li>
<li><a href='http://web.undp.org/geneva/BDP.html'>Bureau for Development Policy</a></li>
<li><a href='http://www.businessfightspoverty.org'>Business Fights Poverty</a></li>
<li><a href='http://www.cmwacameroon.org'>Cameroon Medical Women Association</a></li>
<li><a href='http://www.cbm.org'>CBM</a></li>
<li><a href='#'>Center for Improving Qualified Activity in Life</a></li>
<li><a href='http://www.facebook.ceydesud.com'>Center for Youth Development & Sustainable De</a></li>
<li><a href='http://http://chrds.org/'>Centre for Human Rights and Development Studi</a></li>
<li><a href='http://www.chahtech.com'>chahtech SA</a></li>
<li><a href='http://www.cdapak.org'>Chanan Development Association (CDA) Pakistan</a></li>
<li><a href='http://www.facebook.com/pages/Change-Nepalese-Mission/312706892157401'>Change Nepalese Mission</a></li>
<li><a href='http://www.taopo.org'>Changeneers Digital Incorporated</a></li>
<li><a href='http://www.childfinanceinternational.org'>Child and Youth Finance International</a></li>
<li><a href='http://www.chilfundalliance.org'>ChildFund Alliance</a></li>
<li><a href='http://www.cotef.org'>Children of the Earth</a></li>
<li><a href='http://www.coeworld.org/togo'>Children of the Earth Togo</a></li>
<li><a href='http://www.community.eldis.org/chitsanzo/'>Chitsanzo Youth Organization</a></li>
<li><a href='http://www.cimbthai.com'>CIMB Thai Bank</a></li>
<li><a href='http://www.civicus.org'>CIVICUS: World Alliance for Citien Participat</a></li>
<li><a href='http://www.cividep.org'>Cividep-India</a></li>
<li><a href='http://www.csotwg.org'>Civil Society Organizations Network</a></li>
<li><a href='http://www.crypk.webs.com'>Coalition on Rights & Responsibilities of You</a></li>
<li><a href='http://www.coders4africa.org'>Coders4Aafrica</a></li>
<li><a href='http://http://blogsofbainbridge.typepad.com/adriana/'>Comision Pro fomento Vecinal Cuauhtemoc</a></li>
<li><a href='http://www.ngosbeyond2014.org'>Commonwealth Medical Trust</a></li>
<li><a href='http://www.thecommonwealth.org/subhomepage/152816/'>Commonwealth Youth Programme</a></li>
<li><a href='#'>Community Based Rehabilitation - Development </a></li>
<li><a href='http://www.csgpilipinas.org'>Confederation of student governments of the P</a></li>
<li><a href='http://www.csjoseph.org'>Congregations of Saint Joseph</a></li>
<li><a href='http://www.facebook.com/cooperacoesdeestudos'>Cooperatives de Estudo em Serviso Social</a></li>
<li><a href='http://www.activities.cleanuptheworld.org'>Cosmo Foundation Youth</a></li>
<li><a href='http://www.conpam.ce.gov.br'>Council of Environmental Policies </a></li>
<li><a href='http://www.cry.org'>CRY-Child Rights & You</a></li>
<li><a href='#'>Daughters of Charity</a></li>
<li><a href='http://www.dayofprayerandaction.org'>Day of Prayer and Action for Children </a></li>
<li><a href='http://www.defensores.org'>Defensores PROCDN</a></li>
<li><a href='#'>Development Initiative for Community Enhancem</a></li>
<li><a href='http://www.developmentnewsafrica.com'>Development News Africa</a></li>
<li><a href='http://www.atsiri-indonesia.org'>Dewan Atsiri Indonesia</a></li>
<li><a href='http://www.dpu.ac.th/dpuic'>DPU International College</a></li>
<li><a href='http://www.dripfoundation.org'>DRIP Foundation - Bangladesh</a></li>
<li><a href='#'>Dynamic Youth Development Organization</a></li>
<li><a href='http://www.eapnmadrid.org'>EAPN MADRID</a></li>
<li><a href='http://www.ecoglobala.com'>EcoGlobal</a></li>
<li><a href='http://www.e-alliance.ch'>Ecumenical Advocacy Alliance</a></li>
<li><a href='http://www.epan.com.ng'>Educational Psychology Assocition of Nigeria</a></li>
<li><a href='#'>Emad Karim, M.A, MCSD</a></li>
<li><a href='http://www.emiconsulting-group.net'>Emi Consulting Group</a></li>
<li><a href='http://www.youthenterpriseafrica.org'>Entrepreneurship Initiative for African Youth</a></li>
<li><a href='#'>Ethiopian Change and Development Association</a></li>
<li><a href='http://www.uki.ac.id'>Faculty of Social Sciences and Political Science</a></li>
<li><a href='http://www.atmajaya.ac.id/web/'>Fakultas Hukum Atma Jaya Jakarta</a></li>
<li><a href='http://www.fateconsulting.com'>FATE Consulting Ltd</a></li>
<li><a href='http://www.en.uinjkt.ac.id/'>FISIP UIN Jakarta</a></li>
<li><a href='#'>Forum Masyarakat Katolik indonesia Keuskupan </a></li>
<li><a href='http://www.facebook.com/pages/Forum-Masyarakat-Katolik-Indonesia/124313727679336'>Forum Rakyat Indonesia </a></li>
<li><a href='http://facis.blogspot.com'>Forward in Action for Conservation of Indigen</a></li>
<li><a href='#'>Fosnu Probolinggo </a></li>
<li><a href='#'>Foundation for Environmental Stewardship</a></li>
<li><a href='http://www.youthempowerment.org.ng'>Foundation for Youth Empowerment </a></li>
<li><a href='http://www.hati.my/children/free-relation'>Free Relation</a></li>
<li><a href='http://www.freshandyoungbrains.blogspot.com'>Fresh & Young Brains Development Initiative</a></li>
<li><a href='http://www.doceteomnes.com'>Fundación Docete Omnes</a></li>
<li><a href='#'>GeoPoll </a></li>
<li><a href='http://www.girlscouts.org'>Girl Scouts of the USA </a></li>
<li><a href='http://www.girlsnotbrides.or'>Girls Not Brides</a></li>
<li><a href='http://www.facebook.com/pages/Global-Movement-for-Wildlife-Preservation-Conservation/320290991352689'>Global Alliance for Development Foundation</a></li>
<li><a href='http://www.gadef.org'>Global Call to Action Against Poverty</a></li>
<li><a href='http://www.whiteband.org'>Global Movement for Wildlife Preservation & C</a></li>
<li><a href='http://www.theglobalradio.com'>Global Radio</a></li>
<li><a href='http://www.gsa.org.in'>Global Science Academy</a></li>
<li><a href='http://www.globalthinkersforum.org'>Global Thinkers Forum</a></li>
<li><a href='http://www.globalyounggreens.org'>Global Young Greens</a></li>
<li><a href='http://www.gyef.blog.com'>Global Youth Efficiency Foundation</a></li>
<li><a href='http://www.gyin.org'>Global Youth Innovation Network</a></li>
<li><a href='http://www.globe.com.ph'>Globe Telecom</a></li>
<li><a href='#'>Green Eagle Group</a></li>
<li><a href='http://nygreenumbrella.wordpress.com'>Green Umbrella Youth Group</a></li>
<li><a href='#'>Hatemalo Youth Group</a></li>
<li><a href='http://www.helpage.org'>HelpAge</a></li>
<li><a href='#'>High World International </a></li>
<li><a href='#'>HIJAU.com</a></li>
<li><a href='http://www.hapsarisumut.wordpress.com'>Himpunan Serikat Perempuan Indonesia</a></li>
<li><a href='http://www.hofnacameroon.org'>Hope for the Needy Association </a></li>
<li><a href='http://www.hrwg.org'>HRWG</a></li>
<li><a href='http://www.ideasforus.org'>IDEAS For Us</a></li>
<li><a href='#'>IFIDS - Institute of Financial and Developmen</a></li>
<li><a href='http://www.ibvm.org'>IMBV/LORETO</a></li>
<li><a href='http://www.icmica-miic.org/en/'>IMCS - Pax Romana</a></li>
<li><a href='http://www.facebook.com/Impactwithdanny/info'>Impactwithdanny</a></li>
<li><a href='#'>Individual</a></li>
<li><a href='http://iforhumans.blogspot.com'>Indonesia for Human's</a></li>
<li><a href='http://www.tfcasumatera.org'>Indonesian Biodiversity Foundation</a></li>
<li><a href='http://www.indonesianfutureleaders.org'>Indonesian Future Leaders</a></li>
<li><a href='http://www.pmi.or.id'>Indonesian Red Cross</a></li>
<li><a href='http://www.mpbi.org'>Indonesian Societies for Disaster Management</a></li>
<li><a href='http://www.idyha.org'>Indonesian Youth Health Ambassadors</a></li>
<li><a href='http://www.ihsas.org.pk'>Initiative for Humanity, Social Awareness & S</a></li>
<li><a href='http://www.actionsforyouthburundi.wordpress.com'>Initiatives and Actions for Peace and Develop</a></li>
<li><a href='http://www.facebook.com/pages/INSTITUT-KAPAL-Perempuan/114419281978636'>Institut KAPAL Perempuan</a></li>
<li><a href='http://www.ipu.org'>Inter-Parliamentary Union</a></li>
<li><a href='http://www.interaction.org'>InterAction</a></li>
<li><a href='http://www.interaksyon.com'>InterAksyon</a></li>
<li><a href='http://www.domain-icwecdev.org'>International center for women empowerment & </a></li>
<li><a href='http://www.icrc.org/eng/where-we-work/asia-pacific/indonesia/index.jsp'>International Committee of the Red Cross Indo</a></li>
<li><a href='http://www.ifmsa.org'>International Federation of Medical Students</a></li>
<li><a href='http://www.ilo.org'>International Labour Organization</a></li>
<li><a href='#'>International Program for Law and Sharia, Fac</a></li>
<li><a href='http://www.itu.int'>International Telecommunication Union (ITU)</a></li>
<li><a href='http://www.ituc-csi.org'>International Volunteer Academy</a></li>
<li><a href='http://www.ivacademy.ru'>International Youth Council-Nigeria</a></li>
<li><a href='#'>IOM Media</a></li>
<li><a href='http://www.isodec.org.gh'>ISODEC</a></li>
<li><a href='http://www.facebook.com/istana.rumbia'>Istana Rumbia</a></li>
<li><a href='#'>ITAG Basse Chapter</a></li>
<li><a href='http://www.janegoodall.org/offices'>Jane Goodall Institute Nepal</a></li>
<li><a href='#'>Jaringan Advokasi Rakyat untuk SDA dan Ekosob</a></li>
<li><a href='#'>Jaringan Gay Waria dan LSL lain di Indonesia</a></li>
<li><a href='http://http://www.jklpk-indonesia.org/programs/2011/2012/05/06/3/kampanye-anti-kekerasan-anak-dan-perempuan'>Jaringan Kerja Lembaga Pelayanan Kristen Indo</a></li>
<li><a href='#'>Jatiya Tarun Sangha(JTS)national youth & soci</a></li>
<li><a href='http://www.jevograle.over-blog.org'>Jeunes Volontaires de Grands Lacs pour l'Envi</a></li>
<li><a href='http://www.jzpss.org'>Jhunjhunu Zila Paryavarn Sudhar Samiti</a></li>
<li><a href='http://www.jci.cc'>Junior Chamber International (JCI)</a></li>
<li><a href='http://www.vconnect.com/kadblex-nigeria-enterprises-ikorodu-lagos_b284180'>Kadblex Enterprises</a></li>
<li><a href='http://www.facebook.com/KaribaYouthAssociation?ref=stream'>Kariba Youth Association</a></li>
<li><a href='http://www.kehkashan.urdunama.org'>Kehkashan Development Organization (KDO)</a></li>
<li><a href='#'>Kementrian Luar Negeri Indonesia </a></li>
<li><a href='http://www.khan-foundation.org'>Khan Foundation</a></li>
<li><a href='http://www.kiekare.org'>Kiekare</a></li>
<li><a href='http://www.kingsleycommunitycentre.com'>Kingsley community centre </a></li>
<li><a href='http://www.kophi.or.id'>Koalisi Pemuda Hijau Indonesia</a></li>
<li><a href='http://www.koalisiperempuan.or.id'>Koalisi Perempuan</a></li>
<li><a href='http://www.koc.com.tr/en'>Koc Holding</a></li>
<li><a href='http://www.kowani.or.id'>Kongres Wanita Indonesia</a></li>
<li><a href='http://www.kripafoundation.org'>Kripa Foundation</a></li>
<li><a href='http://www.lakpesdam.or.id'>Lakpesdam NU Ambon</a></li>
<li><a href='#'>Lembaga Pengembangan Sumber Daya Mitra</a></li>
<li><a href='http://www.leoburnett.co.id'>Leo Burnett Jakarta</a></li>
<li><a href='#'>Mahasiswa Akuntansi Stie Nias</a></li>
<li><a href='http://www.makeroadssafe.org'>Make Roads Safe Campaign</a></li>
<li><a href='#'>Marta Benavides</a></li>
<li><a href='http://www.marthatilaar.com'>Martha Tilaar Group of Companies</a></li>
<li><a href='http://www.masrawy.com/'>masrawy.com</a></li>
<li><a href='http://www.mayauniverseacademy.org'>Maya Universe Academy</a></li>
<li><a href='http://www.ngoportal.org/ngo-database-2595-Maynaguri+DISHARI.html'>Maynaguri DISHARI</a></li>
<li><a href='http://www.mdgs.gov.ng'>MDGs Nigeria</a></li>
<li><a href='http://www.migrantcare.net'>Migrant Care</a></li>
<li><a href='#'>Mission For Youth Rights</a></li>
<li><a href='http://www.saynotoviolence.org'>Mujer Para la Mujer A.C. </a></li>
<li><a href='http://www.abim.org.my'>Muslim Youth Movement of Malaysia (ABIM)</a></li>
<li><a href='http://www.mysocialmotion.org'>mysocialmotion</a></li>
<li><a href='http://www.un.org.ec'>Naciones Unidas - Ecuador</a></li>
<li><a href='http://www.NRMnews.com'>Nasionalis Rakyat Merdeka</a></li>
<li><a href='http://www.napc.gov.ph'>National Anti-Poverty Commission Phillippines</a></li>
<li><a href='http://www.nants.org'>National Association of Nigerian Traders</a></li>
<li><a href='http://www.nayd.org'>NEPADCA</a></li>
<li><a href='http://www.redreadi.org'>Network of Euro-Arab NGo for Development</a></li>
<li><a href='http://www.facebook.com/groups/niyoa'>Network of International Youth Organizations </a></li>
<li><a href='http://Newfuturefoundation.com'>New Future Foundation Inc</a></li>
<li><a href='#'>New York Office Volunteers</a></li>
<li><a href='http://www.nnngo.org'>Nigeria Network of NGOs</a></li>
<li><a href='http://www.nooneleftbehind-tanzania.blogspot.com.es'>No One Left Behind- Tanzani</a></li>
<li><a href='http://www.naimun.modelun.org'>North Africa International Model United Natio</a></li>
<li><a href='http://www.northspringshigh.com'>North Springs Charter High School</a></li>
<li><a href='http://www.oyaginaction.webs.com'>Oluwa Youth Activity Group</a></li>
<li><a href='http://www.one.org/international'>ONE Campaign</a></li>
<li><a href='#'>Organisasi Perubahan Sosial Indonesia</a></li>
<li><a href='http://www.geocities.ws/orescameroon'>Organisation for Rural Education Simplicity</a></li>
<li><a href='http://www.liberia.oayouth.org'>Organization of Africa Liberia</a></li>
<li><a href='http://www.oayouth.org'>Organization of African Youth Cameroon</a></li>
<li><a href='http://www.pacificdisability.org;'>Pacific Disability Forum</a></li>
<li><a href='http://www.kemitraan.or.id'>Partnership for Governance Reform</a></li>
<li><a href='http://www.matakin.or.id'>Perempuan Khonghucu Indonesia </a></li>
<li><a href='#'>Perempuan Khonghucu Indonesia Pusat</a></li>
<li><a href='http://www.ohanaindonesia.wordpress.com'>Perhimpunan OHANA</a></li>
<li><a href='http://www.bypides.org'>PIDES International</a></li>
<li><a href='http://www.plan-international.org'>Plan International</a></li>
<li><a href='http://www.peacemfi.org'>Poverty Eradication and Community Empowerment</a></li>
<li><a href='#'>Prefuturo Institute</a></li>
<li><a href='http://www.progressio.org.uk'>Progressio</a></li>
<li><a href='http://www.progressio.ie'>Progressio Ireland</a></li>
<li><a href='#'>Proprint /Philpost</a></li>
<li><a href='http://www.proyectojuandiego.org'>Proyecto Juan Diego</a></li>
<li><a href='http://www.martinaberto.co.id'>PT Martina Berto Tbk</a></li>
<li><a href='#'>Quintiatel</a></li>
<li><a href='http://www.rri.co.id'>Radio Republik Indonesia</a></li>
<li><a href='http://www.redlamyc.info'>REDLAMYC - Latinamerican and Caribbean Networ</a></li>
<li><a href='http://www.rhealsolutions.blogspot.com.es'>Rheal Solutions</a></li>
<li><a href='http://www.rioplustwenties.org'>Rio+Twenties</a></li>
<li><a href='http://www.sjmis.ac.th'>Saint John Mary International School</a></li>
<li><a href='http://www.samarthan.org'>Samarthan - Centre for Development Support</a></li>
<li><a href='http://www.facebook.com/pages/Saving-Lives-Nigeria-SALIN/110079275748506'>Saving Lives Nigeria</a></li>
<li><a href='http://www.facebook.com/SaviorsofEnvironment'>Saviors of Environment</a></li>
<li><a href='http://www.un.org/disabilities/default.asp?id=17'>Secretariat for the Convention on the Rights </a></li>
<li><a href='http://www.seedsforthefuture.com.au'>Seed for the Future</a></li>
<li><a href='#'>SEED India</a></li>
<li><a href='#'>Sekber P.A Sumbar</a></li>
<li><a href='http://www.serac.org'>SERAC-Bangladesh</a></li>
<li><a href='http://www.shikshanepal.com'>Shiksha Nepal</a></li>
<li><a href='http://sisters-of-charity-federation.org'>Sisters of Charity Federation</a></li>
<li><a href='#'>Smiles Africa International</a></li>
<li><a href='#'>Snehal Shah</a></li>
<li><a href='#'>Social justice Office</a></li>
<li><a href='http://www.sos-childrensvillages.org'>SOS Children's Villages</a></li>
<li><a href='http://www.soughtoutcameroon.org'>Sought Out Cameroon </a></li>
<li><a href='http://www.shisindia.org'>Southern Health Improvement Samity </a></li>
<li><a href='http://www.soyda.org/test'>Soyda</a></li>
<li><a href='http://www.spofit.com'>Sports and Fitness Association of Pakistan</a></li>
<li><a href='http://www.stjudethaddeusreliefservices.weebly.com'>St. Jude Thaddeus Relief Services</a></li>
<li><a href='http://www.stakeholderforum.org/sf'>Stakeholder Forum</a></li>
<li><a href='http://startupsauna.com'>Startup Sauna</a></li>
<li><a href='http://www.pps.uin-suka.ac.id'>State Islamic University of Sunan Kalijaga</a></li>
<li><a href='#'>Suara Masyarakat Papua untuk Pasca-2015</a></li>
<li><a href='http://www.clubspeak.org'>Suara Pemuda Anti Korupsi</a></li>
<li><a href='http://www.successgate.com.ng'>SuccessGate </a></li>
<li><a href='http://www.sukoon.com.sa'>Sukoon International</a></li>
<li><a href='http://www.sunfosrilanka.org'>SUNFO</a></li>
<li><a href='http://www.nayd.org/surudev.htm'>Sustainable Run For Development</a></li>
<li><a href='http://www.es.tigweb.org'>TakingITGlobal</a></li>
<li><a href='http://www.tasevder.org'>TASEV Training Culture and Youth Association</a></li>
<li><a href='#'>Teksim3 S. B</a></li>
<li><a href='http://www.greenvolunteers.com'>The Green Volunteers</a></li>
<li><a href='http://www.thegreensworld.org'>The Greens</a></li>
<li><a href='http://www.thelittleart.org'>The Little Art</a></li>
<li><a href='http://www.manilatimes.net'>The Manila Times</a></li>
<li><a href='http://www.tnnthailand.com'>TNN 24 Thailand</a></li>
<li><a href='#'>UCLG</a></li>
<li><a href='#'>Udyamita Evam Kaushal Vikash Sanstha</a></li>
<li><a href='#'>UIN Syarif Hidayatullah Jakarta</a></li>
<li><a href='http://gbgm-umc.org/umw/'>United Methodist Women</a></li>
<li><a href='http://www.uri.org'>United Religions Initiative</a></li>
<li><a href='http://www.budiluhur.ac.id'>Universitas Budi Luhur</a></li>
<li><a href='http://www.unicen.ac.id'>Universitas Cenderawasih Papua</a></li>
<li><a href='#'>Universitas Islam Negeri Jakarta</a></li>
<li><a href='http://www.uinjkt.ac.id'>Universitas Islam Negeri Syarif Hidayatullah </a></li>
<li><a href='http://www.jayabaya.ac.id'>Universitas Jayabaya</a></li>
<li><a href='http://www.uhamka.ac.id'>Universitas Muhammadiyah prof dr HAMKA</a></li>
<li><a href='http://www.umy.ac.id'>Universitas Muhammadiyah Yogyakarta</a></li>
<li><a href='http://www.uny.ac.id'>Universitas Negeri Yogyakarta</a></li>
<li><a href='http://www.uns.ac.id'>Universitas Sebelas Maret</a></li>
<li><a href='http://www.valuesfoundation.in'>Values Foundation</a></li>
<li><a href='http://www.msmgf.org'>Vibrant Youths Community Club</a></li>
<li><a href='#'>Vietnam Association for Protection of Children</a></li>
<li><a href='http://www.viracao.org'>Viracao Educomunicado</a></li>
<li><a href='http://www.vivatinternational.org'>ViVAT International</a></li>
<li><a href='http://voiceofsolidarity.net'>Voice of Solidarity</a></li>
<li><a href='http://www.vsointernational.org'>VSO International</a></li>
<li><a href='http://www.wadanatodo.net'>Wada Na Todo Abhiyan (WNTA)</a></li>
<li><a href='http://www.wbh.or.id'>Wahana Bumi Hijau</a></li>
<li><a href='http://www.walhi.or.id'>Wahana Lingkungan Hidup Inodnesia</a></li>
<li><a href='http://wmydf.webs.com'>Wakiso Muslim Youth Development Foundation</a></li>
<li><a href='#'>Wartawan SIB</a></li>
<li><a href='http://www.weldo.org'>WELDO</a></li>
<li><a href='#'>WeYouth</a></li>
<li><a href='http://www.womanradio.co.id'>Woman Radio</a></li>
<li><a href='http://www.wri.or.id'>Women Research Institute</a></li>
<li><a href='http://www.wgnrr.org'>Women's Global Network for Reproductive Right</a></li>
<li><a href='http://www.wondharmacenter.org'>Won Buddhism International</a></li>
<li><a href='http://www.way.org.my'>World Assembly of Youth</a></li>
<li><a href='http://www.wagggsworld.org'>World Association of Girl Guides and Girl Scouts</a></li>
<li><a href='#'>World Scout Bureau</a></li>
<li><a href='http://www.wscfglobal.org'>World Student Christian Federation</a></li>
<li><a href='http://www.youthaward.org'>World Summit Youth Award</a></li>
<li><a href='http://www.worldvision.or.id'>World Vision Indonesia</a></li>
<li><a href='#'>World Vision International - Latin America & </a></li>
<li><a href='http://www.wya.net'>World Youth Alliance</a></li>
<li><a href='#'>World Youth Conference 2014</a></li>
<li><a href='http://www.worldyouthfoundation.org'>World Youth Foundation </a></li>
<li><a href='http://www.worldywca.org'>World YWCA</a></li>
<li><a href='http://www.worldreader.org'>Worldreader</a></li>
<li><a href='http://www.worldviewmission.org'>Worldview Mission</a></li>
<li><a href='http://www.facebook.com/Ypeerlibya'>Y-peer Libya</a></li>
<li><a href='#'>Yayasan Amanah Pendidik Insan Kamil Lampung</a></li>
<li><a href='http://www.ayad.com.au'>Yayasan Kristen untuk Kesehatan Umum Bali</a></li>
<li><a href='http://www.yhritamilnadu.do.am'>YHRI CUDDALORE</a></li>
<li><a href='http://www.ymca.net'>YMCA</a></li>
<li><a href='http://www.jvecameroun.blogspot.com'>Young Volunteers for Environment Cameroon </a></li>
<li><a href='#'>Youth & Community Empowerment Consultant</a></li>
<li><a href='http://www.peaceforyouth.org'>Youth 4 Peace</a></li>
<li><a href='http://www.facebook/Youth Action and Hope Organization'>Youth Action and Hope Organization</a></li>
<li><a href='http://www.youthaffairsghana.com'>Youth Advocates Ghana-YAG</a></li>
<li><a href='http://www.youthambassadorsblog.wordpress.com'>Youth Ambassadors Rwanda</a></li>
<li><a href='http://www.ydolawrence.org'>Youth Development Organization</a></li>
<li><a href='http://www.youthdividend.org'>Youth Dividend</a></li>
<li><a href='http://www.yeah.org.au'>Youth Empowerment Against HIV/AIDS</a></li>
<li><a href='http://www.yesghana.org'>Youth Empowerment Synergy</a></li>
<li><a href='http://www.palsoftgroup.com/yfwpkenya/index.php'>Youth Federation for World Peace Kenya</a></li>
<li><a href='http://www.yoa.or.tz'>Youth For Africa </a></li>
<li><a href='http://www.youthforhab.org.tr'>Youth for Habitat/Habitat Center for Developm</a></li>
<li><a href='http://www.orgs.tigweb.org/youth-impact-organization-of-nigeria'>Youth Impact Organization of Nigeria</a></li>
<li><a href='http://www.misk.org.kz/about/team.php'>Youth Information Service of Kazakhstan</a></li>
<li><a href='http://www.yice-uganda.org'>Youth Initiative for Community Empowerment</a></li>
<li><a href='http://www.mdgambassadors.org'>Youth Millennium Development Ambassadors Init</a></li>
<li><a href='http://orgs.tigweb.org/youth-network-on-hivaidspopulation-and-development-in-nigeria'>Youth Network on HIV/AIDS, Population and Development</a></li>
<li><a href='http://www.yppdatwork.org'>Youth Partnership for Peace and Development</a></li>
<li><a href='http://twitter.com/Youthfim'>YouthFim</a></li>
<li><a href='http://www.facebook.com/pages/Youthink-Nigeria/576724715678475'>YouThink Nigeria</a></li>
<li><a href='#'>YSA</a></li>
    
</ul>

</article>
<h3><span class="box  arrow-down  color-yellow"></span><a href="#">Private Sector</a></h3>
<article>

<ul>
<li><a href='http://www.pg.com'>Procter & Gamble</a></li>
<li><a href='http://www.viacom.com'>Viacom</a></li>
    
</ul>

</article>
</div>